datasets:
  - tag: defaultGarciaAlonsoPseudotimeEvenCells

method:
  name: ot_cfm
  train_and_test_script: ./methods/ot_cfm/train_and_test.sh

metrics:
  # - name: MetaPerturbation
  - name: MetaPerturbationPerTimepoint
  # - name: StackedBarPlot
  # - name: StackedBarPlot
  #   from_tp_zero: True
