datasets:
  - tag: GarciaAlonsoGC

method:
  name: ot_cfm
  train_and_test_script: ./methods/ot_cfm/train_and_test.sh

metrics:
  - name: MetaPerturbation
    cell_type: pre_spermatogonia
    supported_datasets:
      - GarciaAlonsoDataset
    default_dataset_group: "ontology_based"
    submetrics:
      - name: PerturbationCellTypeProportion
        perturbation_set_config:
          - gene_col_name: gene_symbols
            knockin_genes: ['SOX4', 'EGR4', 'KLF6', 'KLF7']
            knockout_genes: ['STRA8', 'ZGLP1', 'ZIC1']
            timepoint_idx: 0
        trajectory_infer_model:
          name: CellTypist
          renormalize: True
        alias: production

      - name: PerturbationCellTypeProportion
        perturbation_set_config:
          - gene_col_name: gene_symbols
            knockin_genes: ['STRA8', 'ZGLP1', 'ZIC1']
            knockout_genes: ['SOX4', 'EGR4', 'KLF6', 'KLF7']
            timepoint_idx: 0
        trajectory_infer_model:
          name: CellTypist
          renormalize: True
        alias: elimination

      - name: PerturbationCellTypeProportion
        trajectory_infer_model:
          name: CellTypist
          renormalize: True
        alias: control
