datasets:
  - tag: defaultGarciaAlonsoPseudotimeEvenCells

method:
  name: ot_cfm
  train_and_test_script: ./methods/ot_cfm/train_and_test.sh

metrics:
  - name: PerturbationCellTypeProportion
    cell_type: GC
    perturbation_set_config:
      - gene_col_name: gene_symbols
        knockin_genes: ['SOX4', 'EGR4', 'KLF6', 'KLF7']
        knockout_genes: ['STRA8', 'ZGLP1', 'ZIC1']
        timepoint_idx: 4
