datasets:
  # - tag: GarciaAlonsoGC
  - tag: defaultGarciaAlonsoPseudotimeEvenCells

method:
  name: ot_cfm
  train_and_test_script: ./methods/ot_cfm/train_and_test.sh

metrics:
  - name: PerturbationCellTypeProportion
    # this specifies the cell type we want to perturb
    # and we'll be filtering out the cells
    perturbation_set_config:
      filter_cell_type: 'GC'
      filter_tp_idx: 5
      gene_col_name: gene_symbols
      perturbations:
        - knockin_genes: ['SOX4', 'EGR4', 'KLF6', 'KLF7']
          knockout_genes: ['STRA8', 'ZGLP1', 'ZIC1']
          timepoint_idx: 0 # this should be building off of filter_tp_idx
    trajectory_infer_model:
      name: CellTypist
      renormalize: True
  - name: PerturbationCellTypeProportion
    perturbation_set_config:
      filter_cell_type: 'GC'
      filter_tp_idx: 5
      gene_col_name: gene_symbols
      perturbations:
        - knockin_genes: ['STRA8', 'ZGLP1', 'ZIC1']
          knockout_genes: ['SOX4', 'EGR4', 'KLF6', 'KLF7']
          timepoint_idx: 0
    trajectory_infer_model:
      name: CellTypist
      renormalize: True
  - name: PerturbationCellTypeProportion
    perturbation_set_config:
      filter_cell_type: 'GC'
      filter_tp_idx: 5
    trajectory_infer_model:
      name: CellTypist
      renormalize: True
